### PR TITLE
Feature: Dockerify the project

### LINKED ISSUE #16: Add Docker support to the project
For ease of development and deployment, Docker support could be added to the project. This removes the need for dependencies on the developer's local machine (in this case, Go) and provides an easily portable container for developing and distributing.

### Acceptance criteria

- [ ] Add a `Dockerfile` and `docker-compose.yml` for development
- [ ] Running `docker-compose up` runs the server successfully.

### PR DESCRIPTION
**Pull request by DCRichards**
### Description
This project lends itself to being nicely Dockerised for ease of development and deployment.

### Issue

Fixes #16

### Changes

* Added `Dockerfile` and `docker-compose.yml`
* Added very basic `README.md` outlining setup and configuration, with scope for the author to flesh out.
* Fall back to `r.RemoteAddr` if `x-forwarded-for` is not available. Addressing [this comment](https://github.com/rdegges/ipify-api/issues/5#issuecomment-208817089)

### CODE REVIEW

**Comment by DCRichards** [comment]
Any news on this @rdegges? Let me know if there are any changes you'd like made, I realise there are probably some optimisations we can make in the Dockerfile, if it's something you're interested in.

**Comment by C-Duv** [comment]
I ran the Dockerized version using `docker-compose up --build` (after having changed the port, at the 3 locations of `docker-compose.yml`) on Docker v17.05.0-ce and Compose v1.15.0. 
And get `<nil>` answers to my requests.

The `curl -D - 'http://server:9099'` command gets me:
```
HTTP/1.1 200 OK
Content-Type: text/plain
Vary: Origin
Date: Mon, 31 Jul 2017 23:50:31 GMT
Content-Length: 5

<nil>%
```

Docker log shows:
> Attaching to ipifyapi_api_1
api_1  | 2017/07/31 23:50:23 Starting HTTP server on port: 9099
api_1  | WOOT:

**Comment by DCRichards** [comment]
@C-Duv I'm also seeing this, I'm currently investigating

**Comment by DCRichards** [comment]
I have now updated this with a much better Docker solution. I also addressed @C-Duv's issue by falling back to `r.RemoteAddr`, which should prevent the `<nil>`.

**Comment by DCRichards** [comment]
So, it's been just a little while...

**Pull request closed without merging**
